motoURL=https://payseal.icicibank.com/mpi/Moto.jsp
sslURL=https://payseal.icicibank.com/mpi/Ssl.jsp
verbose=true
Key.Directory=d:\home\apeda\public_html\icici_newpg\
OS.Type=NT
epgURL=https://payseal.icicibank.com/mpi/PGServSFA